ACCOUNTS/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views


#template Tagging
app_name = 'ACCOUNTS'

urlpatterns =[
    url('login/',auth_views.LoginView.as_view(template_name='social_media/login.html'), name='login'),
    url ('logout/',auth_views.LogoutView.as_view(), name='logout'),
    url('signup/',views.SignUp.as_view(), name='signup'), 
] 
        

HEALTHproject02/urls.py
from django.contrib import admin
from django.urls import path,include
from ONLINEdata import views
from ACCOUNTS import views
from django.urls import path ,re_path as url

urlpatterns = [
    path('',include('MEDICAL01.urls')),
    path('admin/', admin.site.urls),
    path('ONLINEdata/',include('ONLINEdata.urls')),
    path('pharmacy/',include('PHARMACY.urls')),
    path('accounts/',views.MuhimbiliSocialHomePage.as_view(),name='home'),
    path('accounts/',include('ACCOUNTS.urls' , namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    url('test/',views.TestPage.as_view(), name='test'),
    url('thanks/',views.ThanksPage.as_view(), name='thanks'),
    url('posts/',include('POSTS_SM.urls' , namespace='posts')),
    url('groups/',include('GROUPS_SM.urls' , namespace='groups')),
    path('management/',include('HOSPITAL_MANAGEMENT.urls')),



]

HOSPITAL_MANAGEMENT/urls.py
from django.urls import path
from . import views
from django.conf import settings

#TEMPLATE TAGGING IS BELLOW
app_name = 'HOSPITAL_MANAGEMENT'

urlpatterns =[
    path('', views.manage , name='manage'),
    path('abouts/', views.abouts , name='abouts'),
    path('contacts/', views.contacts , name='contacts'),
]

HOSPITAL_MANAGEMENT/models.py
from django.db import models

# Create your models here.

HOSPITAL_MANAGEMENT/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def manage(request):
    return render(request, 'hospital_management/base.html')

def contacts(request):
    return render(request, 'hospital_management/contacts.html')

def abouts(request):
    return render(request, 'hospital_management/abouts.html')

templates/hospital_management/abouts.html
{% extends "hospital_management/base.html"%}

{% block abouts %}
   <h1 class="text-center" style="margin-top: 50px;">abouts us</h1>
   <div class="container" style="margin-top: 50px;">
    <div class="row">
        <div class="col-md-6">
            <h1 class="strong">who we are <br>
            what we do</h1>
            <p class="lead">this is Tanzania's leading hospital <br>
            we care and treat</p>
        </div>
        <div class="col-md-6">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis atque ducimus laborum, voluptatibus illo rem inventore ea quasi deleniti dolore voluptas dolorum numquam ex facere? Consequatur corrupti eos cupiditate soluta?</p>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Corporis libero perspiciatis nulla quas neque, totam amet rem ducimus veniam aliquam animi consequuntur dolorem ullam porro at asperiores deserunt nisi iste.</p>
        </div>

        <div class="row">
            <div class="site-heading text-center">
                <h3>our team</h3>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Optio reiciendis suscipit, autem dolores deserunt distinctio. Natus alias ut ab voluptatibus dignissimos totam sapiente pariatur officiis, in id tempora laboriosam animi!</p>
                <div class="border"></div>

            </div>
        </div>
    </div>

{% endblock %}

templates/hospital_management/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-grid.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-reboot.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-reboot.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/all.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'js/bootstrap.bundle.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.bundle.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jquery-3.7.0.js' %}">

    

     <!-- below are the links to bootstrap online -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">MUHIMBILI MANAGEMENT SYSTEM</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'HOSPITAL_MANAGEMENT:contacts' %}">CONTACTS</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'HOSPITAL_MANAGEMENT:abouts' %}">ABOUTS</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  LOGINS
                </a>
                <ul class="dropdown-menu">
                  
                  <li><a class="dropdown-item" href="#">DOCTOR</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">ADMIN</a></li>
                </ul>
              </li>
              
            </ul>
          </div>
        </div>
    </nav>

    <h1 class="text-center">welcome to the hospital management system</h1>

    {% block content %}

    {% endblock %}
    
    {% block contacts %}
       <!-- the contacts content -->
    {% endblock %}
    
    {% block abouts %}
       <!-- the abouts content -->
    {% endblock %}
 
    <!--{% include "hospital_management/footer.html" %}   -->
  
    
</body>
</html>

templates/hospital_management/contacts.html
{% extends "hospital_management/base.html"%}






{% block contacts %}

<div class="jumbotron" style="margin-top:50px;">
    <h1 class="text-center">contact us</h1>
    <div class="row mt-5 text-center">
        <div class="col-lg-3 mydivstyle">
            <h4><i class="fas fa-phone-square">Contact</i></h4>
            <p class="text-danger font-weight-bold mt-3"><a href="tel:+255715353219">+255715353219</a></p>
        </div>
        <div class="col-lg-3 mydivstyle">
            <h4><i class="fa fa-envelop">send-email</i></h4>
            <p class="font-weight-bold mt-3"><a href="mailto:muhimbili@gmail.com">muhimbili@gmail.com</a></p>
        </div>
        <div class="col-lg-3 mydivstyle">
            <h4><i class="fa fa-address-card" aria-hidden="true">Hospital Address</i></h4>
            <p class="font-weight-bold mt-3"><a href="http://maps.google.com/maps?q=muhimbili">muhimbili,Dar es salaam</a></p>
        </div>
        <div class="col-lg-3 mydivstyle">
            <h4><i class="fa fa-address-card">office time</i></h4>
            <p class="font-weight-bold mt-3">24 Hrs</p>
        </div>

    </div>

</div>

<!-- the styling of the page -->
<style>
    .mydivstyle:hover{
        box-shadow: 0 0 20px 0 rgba(0,0,0,0.3);
        transform: translatey(-20px);
    }
</style>


{% endblock %}

templates/hospital_management/footer.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom">
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
             <div class="col-sm-12 text-center">
                <div class="copyright-text">
                    <p class="text-white">A small team with big ideas</p>
                </div>
             </div>
            </div>
        </div>
    </div>
</nav>