ACCOUNTS/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views


#template Tagging
app_name = 'ACCOUNTS'

urlpatterns =[
    url('login/',auth_views.LoginView.as_view(template_name='social_media/login.html'), name='login'),
    url ('logout/',auth_views.LogoutView.as_view(), name='logout'),
    url('signup/',views.SignUp.as_view(), name='signup'), 
] 
        

GROUPS_SM/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings



#template Tagging
app_name = 'GROUPS_SM'

urlpatterns =[
    url('groups/',views.ListGroups.as_view(), name='all'),
    url ('new/',views.CreateGroup.as_view(), name='create'),
    url('posts/in/(?P<slug>[-\w]+)/',views.SingleGroup.as_view(), name='single'),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url('leave/(?P<slug>[-\w]+)/',views.LeaveGroup.as_view(),name='leave'), 
] 
        

HEALTHproject02/urls.py
from django.contrib import admin
from django.urls import path,include
from ONLINEdata import views
from ACCOUNTS import views
from django.urls import path ,re_path as url

urlpatterns = [
    path('',include('MEDICAL01.urls')),
    path('admin/', admin.site.urls),
    path('ONLINEdata/',include('ONLINEdata.urls')),
    path('pharmacy/',include('PHARMACY.urls')),
    path('accounts/',views.MuhimbiliSocialHomePage.as_view(),name='home'),
    path('accounts/',include('ACCOUNTS.urls' , namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    url('test/',views.TestPage.as_view(), name='test'),
    url('thanks/',views.ThanksPage.as_view(), name='thanks'),
    url('posts/',include('POSTS_SM.urls' , namespace='posts')),
    url('groups/',include('GROUPS_SM.urls' , namespace='groups')),
    path('management/',include('HOSPITAL_MANAGEMENT.urls')),



]

POSTS_SM/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings

#for template tagging
app_name = 'POSTS_SM'

urlpatterns =[
    url('posts/',views.PostList.as_view(), name='all'),
    url ('new/',views.CreatePost.as_view(), name='create'),
    url('by/(?P<username>[-\w]+)',views.UserPosts.as_view(), name='for_user'),
    url('by/(?P<username>[-\w]+)/(?P<pk>\d+)/',views.PostDetail.as_view(), name='single'),
    url('delete/(?P<pk>\d+)/', views.DeletePost.as_view(), name='delete')
] 
        

templates/social_media/base_social.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>social media</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-grid.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-reboot.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-reboot.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/all.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'js/bootstrap.bundle.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.bundle.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
    <link rel="stylesheet" href="{% static 'js/jquery-3.7.0.js' %}">

    <!-- the start of some java script files included and effects  -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-1.6.3.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.7.0.js' %}"></script>
    <link rel="stylesheet" href="{% static 'js/jquery-3.7.0.js' %}">




</head>
<body>
    <nav class="navbar">
       <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">MUHIMBILI SOCIAL MEDIA</a>
         <ul class="nav navbar-nav navbar-right">
         {% if user.is_authenticated %}
          <li><a href="{% url 'POSTS_SM:create' %}">POST</a></li>
          <li><a href="{% url 'GROUPS_SM:all' %}">GROUPS</a></li>
          <li><a href="{% url 'GROUPS_SM:create' %}">CREATE GROUPS</a></li>
          <li><a href="{% url 'ACCOUNTS:logout'%}">log-out</a></li>
         {% else %} 
          <li><a href="{% url 'GROUPS_SM:all' %}">GROUPS</a></li>
          <li><a href="{% url 'ACCOUNTS:login'%}">log-in</a></li>
          <li><a href="{% url 'ACCOUNTS:signup'%}">sign-up</a></li>
         {% endif %}
        </ul>
       </div>
    </nav>


<div class="container">
{% block content %}


{% endblock %}
</div>
    
</body>
</html>

templates/social_media/login.html
{% extends "social_media/base_social.html"%}
{% load bootstrap3 %}

{% block content %}
<h1>plaese sign up herre</h1>

<div class="container">
    <h1>log-In</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="sign Up">
    </form>
</div>
{% endblock%}

templates/social_media/sign_up.html
{% extends "social_media/base_social.html"%}
{% load bootstrap3 %}

{% block content %}
<h1>plaese sign up herre</h1>

<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="sign Up">
    </form>
</div>
{% endblock%}

templates/social_media/social.html
{% extends "social_media/base_social.html"%}
{% block content %}
<h1>hello</h1>

{% endblock %}