ACCOUNTS/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views


#template Tagging
app_name = 'ACCOUNTS'

urlpatterns =[
    url('login/',auth_views.LoginView.as_view(template_name='social_media/login.html'), name='login'),
    url ('logout/',auth_views.LogoutView.as_view(), name='logout'),
    url('signup/',views.SignUp.as_view(), name='signup'), 
] 
        

GROUPS_SM/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings



#template Tagging
app_name = 'GROUPS_SM'

urlpatterns =[
    url('groups/',views.ListGroups.as_view(), name='all'),
    url ('new/',views.CreateGroup.as_view(), name='create'),
    url('posts/in/(?P<slug>[-\w]+)/',views.SingleGroup.as_view(), name='single'),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url('leave/(?P<slug>[-\w]+)/',views.LeaveGroup.as_view(),name='leave'), 
] 
        

HEALTHproject02/urls.py
from django.contrib import admin
from django.urls import path,include
from ONLINEdata import views
from ACCOUNTS import views
from django.urls import path ,re_path as url

urlpatterns = [
    path('',include('MEDICAL01.urls')),
    path('admin/', admin.site.urls),
    path('ONLINEdata/',include('ONLINEdata.urls')),
    path('pharmacy/',include('PHARMACY.urls')),
    path('accounts/',views.MuhimbiliSocialHomePage.as_view(),name='home'),
    path('accounts/',include('ACCOUNTS.urls' , namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    url('test/',views.TestPage.as_view(), name='test'),
    url('thanks/',views.ThanksPage.as_view(), name='thanks'),
    url('posts/',include('POSTS_SM.urls' , namespace='posts')),
    url('groups/',include('GROUPS_SM.urls' , namespace='groups')),
    path('management/',include('HOSPITAL_MANAGEMENT.urls')),



]

POSTS_SM/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings

#for template tagging
app_name = 'POSTS_SM'

urlpatterns =[
    url('posts/',views.PostList.as_view(), name='all'),
    url ('new/',views.CreatePost.as_view(), name='create'),
    url('by/(?P<username>[-\w]+)',views.UserPosts.as_view(), name='for_user'),
    url('by/(?P<username>[-\w]+)/(?P<pk>\d+)/',views.PostDetail.as_view(), name='single'),
    url('delete/(?P<pk>\d+)/', views.DeletePost.as_view(), name='delete')
] 
        

GROUPS_SM/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm 
from ACCOUNTS.models import User
from django.urls import reverse_lazy
from django.urls import reverse


#the bellow imported model makes the  url to be more compatible to the browsers by removng spaces and other unwanted features in the string of url 
from django.utils.text import slugify

#returns the current user mode active ,enable to call things outside the user
from django.contrib.auth import get_user_model
user = get_user_model()

#allows the use of custom template .... thus allows to use the RELATED NAMES assigned to a class to call the class in template syntax and tagging
from django import template
register = template.Library()



# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    members = models.ManyToManyField(User,through='GroupMember')


    def __str__(self):
        return self.name
    
    #the super() saves all data in the class
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)
    

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name'] 
    

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships', on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User,related_name='user_groups', on_delete=models.DO_NOTHING)

    #for the string representation of the user shhown in the data base
    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together = ('group','user')

GROUPS_SM/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect

from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import IntegrityError
from ACCOUNTS.models import User

from django.contrib.auth.models import User
 

from . import models
#importing the model enables the linking of the views to the model
from GROUPS_SM.models import Group, GroupMember


# Create your views here.
# CBV are also included
 

#the view below is connected to the Group.model thus when called enbles the user to make/edit the listed fields
class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name', 'description') 
    model = Group

#shows the details of the group like posts .... through the CBV fx
class SingleGroup(generic.DetailView):
    model = Group
    template_name = 'groups_sm/group_details.html'

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))
        
        try:
          
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

           

        template_name = 'groups_sm/group_details.html'

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})
    
    #to check if the user bellongs in the grp
    def get(self,request,*args,**kwargs):

        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kqargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group')
        else:
            membership.delete()
            messages.success(self.request,'you have left the group')
        return super().get(request,*args,**kwargs)


      

templates/groups_sm/group_base.html
<!-- this is the page which contain base features of the group templates -->

{% extends "social_media/base_social.html"%}
{% block content %}
<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>
{% endblock %}

templates/groups_sm/group_details.html
{% extends "groups_sm/group_base.html" %}

{% block pregroup %}

<h1>{{group.name}}</h1><br>
<h2>Member Count : {{group.member.count}}</h2><br>

<div class="content">
    {% if user in group.members.all %}
      <a href="{% url 'GROUPS_SM:leave' slug=group.slug %}"
       class="btn btn-lg btn-fill btn-warning">
       <span class="glyphicon glyphicon-remove-circle"></span>Leave</a>


    {% else %}
      <a href="{% url 'GROUPS_SM:join' slug=group.slug %}"
       class="btn btn-lg btn-fill btn-warning">
       <span class="glyphicon glyphicon-ok-circle"></span>join</a>
    {% endif %}
</div>

{% endblock %}


{% block group_content %}

<div class="col-md-8">
    {% if group.posts.count == 0 %}
      <h2>NO POSTS IN THE GROUP YET!</h2>

    {% else %}

      {% for post in group.posts.all %}
        {% include "posts_sm/_post.html"%} 
      {% endfor %}
      
    {% endif %}
</div>

{% endblock %}

templates/groups_sm/group_form.html
<!-- this page is for the user which wants to create a new group -->

{% extends "groups_sm/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}

<h4>create a new group!</h4>

 <form action="{% url 'GROUPS_SM:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="create">
 </form>

{% endblock %}

templates/groups_sm/group_list.html
<!-- this page displays the list of groups present -->

{% extends "groups_sm/group_base.html"%}

<!-- the start of the pregroup block -->
{% block pregroup %}

<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
          <h2>Welcome Back 
            <a href="{% url 'POSTS_SM:for_user' username=user.username %}">
            @{{user.username}}
          </a>
         </h2>
        {% endif %}

        <h2>GROUPS</h2>
        <p>welcome to the groups page !</p>
    </div>

    {% if user.is_authenticated %}
      <a href="{% url 'GROUPS_SM:create' %}" class="btn btn-md btn-fill btn-warning">
        <span class="glyphicon glyphicon-plus-sign">Create new Group </span>
      </a>
    {% endif %}

</div>
{% endblock %}
<!-- the end of the pregroup block -->




<!-- the start of the group_content block -->
{% block group_content %}

<div class="col-md-8">
    <div class="list-group">
        {% for group in object_list %}
          <a class='list-group-item' href="{% url 'GROUPS_SM:single' slug=group.slug %}">
            <h3 class="title list-group-item-heading">{{group.name}}</h3>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4">
                        <span class="badge">{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                    </div>
                    <div class="col-md-4">
                        <span class="badge">{{group.members.count}}</span>
                        post{{group.members.count|pluralize}}
                    </div>
                </div>
            </div>
          </a>
        {% endfor %}
    </div>
</div>

{% endblock %}
<!-- the end of the  group_content block  -->