ACCOUNTS/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views


#template Tagging
app_name = 'ACCOUNTS'

urlpatterns =[
    url('login/',auth_views.LoginView.as_view(template_name='social_media/login.html'), name='login'),
    url ('logout/',auth_views.LogoutView.as_view(), name='logout'),
    url('signup/',views.SignUp.as_view(), name='signup'), 
] 
        

GROUPS_SM/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings



#template Tagging
app_name = 'GROUPS_SM'

urlpatterns =[
    url('groups/',views.ListGroups.as_view(), name='all'),
    url ('new/',views.CreateGroup.as_view(), name='create'),
    url('posts/in/(?P<slug>[-\w]+)/',views.SingleGroup.as_view(), name='single'),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url('leave/(?P<slug>[-\w]+)/',views.LeaveGroup.as_view(),name='leave'), 
] 
        

HEALTHproject02/urls.py
from django.contrib import admin
from django.urls import path,include
from ONLINEdata import views
from ACCOUNTS import views
from django.urls import path ,re_path as url

urlpatterns = [
    path('',include('MEDICAL01.urls')),
    path('admin/', admin.site.urls),
    path('ONLINEdata/',include('ONLINEdata.urls')),
    path('pharmacy/',include('PHARMACY.urls')),
    path('accounts/',views.MuhimbiliSocialHomePage.as_view(),name='home'),
    path('accounts/',include('ACCOUNTS.urls' , namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    url('test/',views.TestPage.as_view(), name='test'),
    url('thanks/',views.ThanksPage.as_view(), name='thanks'),
    url('posts/',include('POSTS_SM.urls' , namespace='posts')),
    url('groups/',include('GROUPS_SM.urls' , namespace='groups')),
    path('management/',include('HOSPITAL_MANAGEMENT.urls')),



]

POSTS_SM/urls.py
from django.urls import path ,re_path as url
from . import views
from django.conf import settings

#for template tagging
app_name = 'POSTS_SM'

urlpatterns =[
    url('posts/',views.PostList.as_view(), name='all'),
    url ('new/',views.CreatePost.as_view(), name='create'),
    url('by/(?P<username>[-\w]+)',views.UserPosts.as_view(), name='for_user'),
    url('by/(?P<username>[-\w]+)/(?P<pk>\d+)/',views.PostDetail.as_view(), name='single'),
    url('delete/(?P<pk>\d+)/', views.DeletePost.as_view(), name='delete')
] 
        

POSTS_SM/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


from GROUPS_SM.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()



# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts', on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.DO_NOTHING)


    def __str__(self):
        return self.message
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':self.user.username, 'pk':self.pk})
    
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']
    

POSTS_SM/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from braces.views import SelectRelatedMixin
from django.http import Http404

from . import models
from . import forms

from django.contrib import messages


from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

#list of posts in a group
class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user','group')

#the list of posts of the user
class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts_sm/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
          raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['post_user'] = self.post_user
       return context
    


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__name__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('message', 'group')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
    

class DeletePost(LoginRequiredMixin, SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')  #uses template tagging

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)
    
    def delete(self,*args,**kwargs):
        messages.success(self.request,'post Deleted')
        return super().delete(*args,**kwargs)

templates/posts_sm/_post.html
<!-- this file is used for injecting features to other post pages -->
<!-- this is applied to the tamplates which become too big -->
<!-- by using the INCLUDE tag -->

<div class="post media">
    <h3>{{post.message_html|safe}}</h3>

    <div class="media-body">
        <strong>{{post.user.username}}</strong>
        <h5 class="media-heading">
            <span>
                <a href="{% url 'POSTS_SM:for_user' username=post.user.username %}"></a>
            </span>
            <time class="time">
                <a href="{% url 'POSTS_SM:single' username=post.user.username pk=post.pk %}"></a>
            </time>
        </h5>

        <div class="media-footer">

            {% if user.is_authenticated and post.user == user %}
              <a href="{% url 'POSTS_SM:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
                <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                <span class="text-danger icon-label">DELETE</span>  
            </a>
            {% endif %}
        </div>
        
    </div>

</div>

templates/posts_sm/post_base.html
<!-- this is the page for the base features of the post templates  -->

{% extends "social_media/base_social.html"%}

{% block content %}
<div class="posts-page">
    <div class="container">
        <div class="row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post %}{% endblock %}
    
        </div>
    </div>
</div>
{% endblock %}

templates/posts_sm/post_confirm_delete.html
<!-- this id the page that asks for confirmation of deleting a post -->

{% extends "posts_sm/post_base.html" %}

{% block post_content %}
<h3>Are you sure you want to delete post </h3>

<div class="posts">
    {% include "posts_sm/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
    {%csrf_token%}
    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
    <a href="{% url 'POSTS_SM:single' username=user.username pk=object.pk %}">
        cancel
    </a>
</form>

{% endblock %}

templates/posts_sm/post_detail.html
<!-- this page shows the details of the post -->

{% extends "posts_sm/post_base.html" %}
  
{% block post_content%}

<div class="col-md-8">
    {% include "posts_sm/_post.html" %}
</div>

{% endblock %}

templates/posts_sm/post_form.html
<!-- this page is for creating a new post -->

{% extends "posts_sm/post_base.html" %}
 
{% load bootstrap3 %}

{% block post_content %}
<h4>Create a new Post </h4>

<form action="{% url 'POSTS_SM:create' %}" method="POST">

    {%csrf_token%}
    {% bootstrap_form form %}
    <input type="submit" value="POST" class="btn btn-primary btn-large">

</form>

{% endblock %}

templates/posts_sm/post_list.html
<!-- this page contains the list of all posts made by users -->

{% extends "posts_sm/post_base.html" %}

{% block pre_post %}

<div class="col-md-4">

    {% if request.user.is_authenticated %}
      <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">your Groups</h5>
            <ul class="list-unstyled">
                {% for member_group in get_user_groups %}
                  <li class="group li-with-bullet">
                    <a href="{% url 'GROUPS_SM:single' slug=member_group.group.slug %}"></a>
                  </li>
                {% endfor %}
            </ul>
        </div>
      </div>
    {% endif %}

    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">all Groups</h5>
            <ul class="list-unstyled">
                {% for other_group in get_other_groups %}
                <li class="group li-with-bullet">
                    <a href="{% url 'GROUPS_SM:single' slug=other_group.slug %}"></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

{% block post_content %}
<div class="col-md-8">

    {% for post in post_list %}
      {% include "posts_sm/_post.html"%}
    {% endfor%}

</div>

{% endblock%}

templates/posts_sm/user_post_list.html
<!-- the page contains the posts or feeds of the user -->

{% extends "posts_sm/post_base.html" %}

{% block prepost %}

  <div class="col-md-4">
    <h1>@{{post_user.username}}</h1>
  </div>

{% endblock %}


{% block post_content %}

<div class="col-md-8">
    {% for post in post_list %}
      {% include "posts_sm/_post.html"%}
    {% endfor %}
</div>

{% endblock %}